name: AWS OIDC Test

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:

  test:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ap-southeast-2

      - name: Verify AWS Access
        run: |
          aws sts get-caller-identity
      - name: Test S3
        run: |
            echo "hello" > test.txt

            aws s3 cp test.txt \
            s3://laravel-auto-deploy-mike/test.txt